# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('adressFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offerStream.Adress')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='storeFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offerStream.Store'),
        ),
    ]
